# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fb070dd776456c45b36e5cbc1d60b620575eab49df3ad87c4464108dcd9115e20909f4eb7dea0929dfd699ffd7508226b1ece773a051df6b9c7ecda1ad67ec5

test:
  secret_key_base: ebe3cf09c492e649d77eba5c13e4a58aa48e1b37ae74d4b10f70e33aac22c45e58081d46c39ebb1aa280385737d208218d29426a60419cef2170cb42208e402f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
